apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: glpiweb
  template:
    metadata:
      labels:
        app: glpiweb
    spec:
      containers:
      - name: glpiweb
        image: inerente/glpi-suse:v1
        resources:
          limits:
            memory: "3072Mi"
            cpu: "2000m"
        ports:
          - containerPort: 80
        env:
          - name: MARIADB_PORT
            value: "3306"
          - name: DB_HOST
            value: "mariadb-service"

---

apiVersion: v1 
kind: Service
metadata:
  name: glpi-service
spec:
  selector:
    app: glpiweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: inerente/mariadb:v1v
        resources:
          limits:
            memory: "3072Mi"
            cpu: "2000m"
        ports:
          - containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: lkjasdf
          - name: MARIADB_DATABASE
            value: glpi10
          - name: DB_HOST
            value: mariadb-service

---

apiVersion: v1 
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP